language: cpp
compiler: gcc
os:
    #    - linux
    - osx
osx_image: xcode9.2
env:
    - BUILD_PY=2.7
    - BUILD_PY=3.5
    - BUILD_PY=3.6
    - BUILD_PY=3.7
before_install:
    - MINICONDA_VERSION=latest
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
    - if [[ "$BUILD_PY" == "2.7" ]]; then MINICONDA_PY=2; else MINICONDA_PY=3; fi
    - wget https://repo.anaconda.com/miniconda/Miniconda$MINICONDA_PY-$MINICONDA_VERSION-$MINICONDA_OS-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p "$HOME"/miniconda
    - source "$HOME"/miniconda/etc/profile.d/conda.sh
    - hash -r 
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda install conda-build
    - conda config --add channels conda-forge
    - conda config --add channels demorest
    - conda info -a
    - export LANG=en_US.UTF-8
install:
    - git clone --depth=1 git://git.code.sf.net/p/dspsr/code dspsr
    # Could get the number of commits on a given date like:
    # git -C dspsr log --format="%cd" --date=short | uniq -c | head -n1
    # Then split it up inside the meta.yaml.
    - export VERSION=$(git -C ./dspsr log -1 --format='%cd' --date=short | sed 's/-/./g')
    - conda build --python $BUILD_PY ./recipe
    - conda create -n test --use-local dspsr
script:
    - conda activate test
    - dspsr -h
    - python -c 'import dspsr'
#after_success:
#    - export PKGFILE=$(conda build --python $BUILD_PY ./recipe --output)
#    - conda install anaconda-client
#    - anaconda -t $CONDA_UPLOAD_TOKEN upload -u demorest --force $PKGFILE
